### ISSUE TITLE
Can I use deck chores to start a container to run a command, or must it already be running?

### ISSUE THREAD

**Issue by psyciknz** [funkyfuture/deck-chores#100]
Is this where I'd use this function: https://deck-chores.readthedocs.io/en/stable/usage.html#containers-without-an-enduring-main-process

**Comment by psyciknz** [comment]
Hi, any possible answer to this?  I like the idea of having all my crons in docker-compose files rather than on the host.

**Comment by funkyfuture** [comment]
could you please be specific with your inquiry?

**Comment by funkyfuture** [comment]
the docs contain a hint how to start a container whose main process is a no-op.

**Comment by psyciknz** [comment]
You mean this section?

Containers without an enduring main process

If the container is supposed to only run the scheduled commands and not a main process, use a non-stopping no-op command as main process like in this snippet of a docker-compose.yml file:

services:
  neverending:
    # …
    command: tail -f /dev/null
    labels:
      deck-chores.daily_job.command: daily_command …
      deck-chores.daily_job.interval: daily


So dues that mean I have to convert a container that isn’t running permanently to a permanent one via the tail command (or like).  And then I can run commands against it?


As opposed to starting a stopped container to run a task
