### ISSUE TITLE
APK packages should not be upgraded.

### ISSUE THREAD

**Issue by bddenhartog** [funkyfuture/deck-chores#11]
Upgrading system packages easily leads to changed state within an image, and containers that are started from updated images. To install `tini`, all you really need are for the repository indexes to be updated. `apk add --update --no-cache tini` can be used to install the dependency instead.

Additionally, `tini` should be installed at a pinned version to maintain container immutability. The current latest version is `0.9.0-r1`.

**Comment by funkyfuture** [comment]
but that happens when the images are built, not in a created container. the images are tested.

**Comment by bddenhartog** [comment]
Yes, I updated my comment for clarity. You definitely could continue to upgrade all system packages on build and install the latest versions of dependencies, but you're allowing the introduction changes to your image that aren't intentional by doing so. Upgrading system packages could easily cause problems for images that depend on yours. 

Why introduce passive mutation?

**Comment by funkyfuture** [comment]
there's currently not stateful data or even any volume deffined that would persist state atm.

if there's a conrete issue with a derived image, reopen this issue with a description of that issue.

**Comment by bddenhartog** [comment]
> there's currently not stateful data or even any volume deffined that would persist state atm

I never mentioned state. Let's pretend you depend on `wget` to build your image, and `python:3.6` is updated to include some changes from _their_ upstream. In that update, the functionality of `wget` changes.

Now you can't build your image on a new host, and you're borked. Any users who extend your image using latest is also borked.

See docker/docker#11109 for more information.
