### ISSUE TITLE
Docker Hub image seems corrupt ?

### ISSUE THREAD

**Issue by fhaefemeier** [funkyfuture/deck-chores#110]
After pull the image locally it can be used to create a container. But I use Nexus server to cache the images from docker hub. This has a feature to check and delete unused manifests and images from cache. These special task raise an exception if the image funkyfuture/deck-chores is cached. The [Nexus support](https://issues.sonatype.org/browse/NEXUS-37510) tells the image manifest is out of specification.
Docker Hub web UI provide the feature to list all tags. If you go there and click on a tag the page shows nothing. Normally the image layer is shown.
Is there something special how the image is created?

**Comment by funkyfuture** [comment]
i can't access the URL that you posted, please post the information if it points to a problem.

i assume you're not seeing what you expect on the Docker Hub b/c the image is built [with GitHub Actions](https://github.com/funkyfuture/deck-chores/blob/main/.github/workflows/build-and-publish.yml) and not on the Hub.

**Comment by funkyfuture** [comment]
i assume that there was a misconception how the images are built.
