### ISSUE TITLE
Enhancement request:  pre and post execution hook/script

### ISSUE THREAD

**Issue by psyciknz** [funkyfuture/deck-chores#119]
I’ve just started using healthchecks.io, but before that had calls to pushover built into some of my bash commands.

But what do you think about the ability to set a pre/post command as part of the job definition.   Even if it’s just a script name.

For healthchecks.io you just run a curl command to a specific url.  So that would be handy, but I think most versatile would be do define a pre script and/or post script where the user can write what they want.

So a definition might look like this:

```

deck-chores.job-ytdl.precommand: /user/script/on/docker.host
deck-chores.job-ytdl.command: bash -c "/config/runupdate.sh"
deck-chores.job-ytdl.cron: "* * * */6 1 0 "
deck-chores.job-ytdl.postcommand: /user/script/on/docker.host
```

**Comment by funkyfuture** [comment]
there are two ways that you can achieve what you want:

- extend the commands that you pass to bash, e.g. `bash -c "/user/script/in/container ; /config/runupdate.sh ; …"`
- or extend the `runupddate.sh` script

so, the versatility is there. no need to re-invent anything.
