### ISSUE TITLE
Update cron usage documentation

### ISSUE THREAD

**Issue by etki** [funkyfuture/deck-chores#13]
Hi!

First of all, i want to thank you for the tool. It perfectly suites our needs and i couldn't find anything else like that.

Currently docs for cron trigger are little vague. It's not clear which position in expression stands for what, and provided link seems to be broken. I think it would be great to add little explanation about how the expression is parsed and what each position means, because it is not fully interchangeable with standard cron expression.

**Comment by funkyfuture** [comment]
yes, that certainly is an issue. would you provide a patch?

i tried to express that it is cron-*like*. if you came across a phrase where this is not clear (but rather that it is identical to cron), that should be clarified too.

here's the current link to the intended reference: https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#expression-types

**Comment by etki** [comment]
@funkyfuture i've tried to dive into source code, but i'm lacking knowledge of python and libraries. I understand that somewhere CronTrigger class is created but i'm not sure how the expression is parsed and passed to it. Am i right that currently expression is split by whitespace, then extra arguments are prepended and then the result is used as arguments for CronTrigger constructor?

**Comment by funkyfuture** [comment]
exactly. :-)

**Comment by etki** [comment]
ok, i'll send pull request sometime (this may take a while, i gave lots of such promises atm D:)

**Comment by courcelm** [comment]
+1 
Doc is not clear on this topic

**Comment by funkyfuture** [comment]
just pushed an update of the docs, reviews are appreciated.
