### ISSUE TITLE
documentation says 'permission denied'

### ISSUE THREAD

**Issue by bartb** [funkyfuture/deck-chores#23]
http://deck-chores.readthedocs.io/en/master/

Documentation says:

## Permission Denied

You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.

**Comment by funkyfuture** [comment]
where did you obtain that URL? it's `…/latest/" or just the fqdn.

**Comment by bartb** [comment]
Weird, I just clicked on the link in the readme github file.
But it automagically redirects me to http://deck-chores.readthedocs.io/en/master/

Going directly to http://deck-chores.readthedocs.io/en/latest/ works as expected.

**Comment by bartb** [comment]
By the way, great project!! Saves my a lot of work.

**Comment by funkyfuture** [comment]
yep, same for my browser. `latest` is configured to be redirected from `/` to, but reditects to `master`.

it could be caused by the same bug like https://github.com/rtfd/readthedocs.org/issues/2151
