### ISSUE TITLE
Trigger all scheduled commands manually

### ISSUE THREAD

**Issue by binnisb** [funkyfuture/deck-chores#24]
Hey.

I have few things that run on a daily basis, but occasionally I would like to run them an extra time manually. Is this possible?

**Comment by funkyfuture** [comment]
`docker exec <container> <command>`, i'd say.

**Comment by binnisb** [comment]
Well that is of course what I do now :) I just wondered if it would be possible to issue a command to deck-chores container to run all registered jobs, since it takes some time to go through all commands I have already.  So consider this a feature request, with low prio.

**Comment by funkyfuture** [comment]
okay, but that'd require some refactoring with regards to subcommands and interprocess communication.

if you can sketch the command's design, that would be very helpful.

**Comment by funkyfuture** [comment]
here are some of the prerequisites that need to be addressed:

- [ ] introduce subcommands with the `daemon` command as default
- [ ] store the daemon's pid in the filesystem
- [ ] layout the syntax of a `trigger` subcommand
- [ ] implement a signal handler that reads jobs to be triggered from a shared mmap-file and triggers them

**Comment by dperetti** [comment]
Probably related : it would be great to have a label that means "also run the command when deck-chores" starts, so we can for instance renew a Let's Encrypt certificate daily but also initially, as soon as the docker swarm is deployed.

**Comment by funkyfuture** [comment]
@dperetti why don't you call such jobs from an `entrypoint.sh` or similar?

**Comment by funkyfuture** [comment]
i'm closing this issue, because both requested features can be achieved by adding scripts to a container. for @binnisb i see that it would be simpler to hit all configured jobs, but `deck-chores`' architecture will not change significantly, which would be necessary.

**Comment by Shawak** [comment]
I am having the same issue. Entrypoint and command is already in use, would be cool to have such a feature since it would result in a better maintainability.

**Comment by funkyfuture** [comment]
you can add an alternate entrypoint to a derived image and `exec` the original entrypoint from the added one.

**Comment by funkyfuture** [comment]
um, let's say an interface for manual interactions is thinkable with a shared state storage which i mentioned [here](https://www.reddit.com/r/docker/comments/fr6taz/two_days_ago_i_released_deckchores_10_a_job/fm5iq3y/).
