### ISSUE TITLE
Schedule exited containers

### ISSUE THREAD

**Issue by binnisb** [funkyfuture/deck-chores#25]
I see this in the log:

```bash
2017-08-28 09:38:59,967|INFO    |Locking service id: xxxyyy
2017-08-28 09:38:59,970|INFO    |Added 'scheduled' for demo
2017-08-28 09:39:11,648|INFO    |Unlocking service id: xxxyyy
2017-08-28 09:39:11,838|INFO    |Removing job 'scheduled' for demo
```
The demo container runs a single command and then exits, so it is in Exited(0) state. Is it then correctly understood that I can't have deck-chore run the container when exited? Would it be possible to add an option to have it start the container?

**Comment by funkyfuture** [comment]
i'm not sure, whether i'm understanding the scenario. more details would be helpful.

> Is it then correctly understood that I can't have deck-chore run the container when exited?

no, deck-chores does not control containers. it just observes them and executes commands *within* containers.

**Comment by binnisb** [comment]
I realized that I then need docker compose to run the container with a
command like
```bash
tail -f /dev/null
```
To start the container and keep it running, while I'll let the deck-chores
run the scheduled command.

**Comment by funkyfuture** [comment]
you could amend this in a "Tips" (or something similar) section in the `usage.rst`.

**Comment by funkyfuture** [comment]
closing this now with regards to #26, which i will merge before the next release.
