### ISSUE TITLE
Check cron example code

### ISSUE THREAD

**Issue by alpine-digger** [funkyfuture/deck-chores#27]
In [cron examle code](https://deck-chores.readthedocs.io/en/latest/usage.html#examples) there is used for run command every Sunday this code:

`* * * * 7 1 0 0    # run every Sunday at 1:00`

but according to [APScheduler API](https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#api) day_of_week accept these value:

`day_of_week (int|str) – number or name of weekday (0-6 or mon,tue,wed,thu,fri,sat,sun)`

So what is correct? Number 6 or 7?

**Comment by funkyfuture** [comment]
thanks for spotting this, it should be `6`. a pr to fix this and an additon with `sun` as alternative is welcome.

**Comment by funkyfuture** [comment]
Solved in 003c83a787c6e9ce0be44d0bda1c88fe5620e57d.
