### ISSUE TITLE
RANCHER | TIMEZONE  Environment Variable seem not work

### ISSUE THREAD

**Issue by HBO2** [funkyfuture/deck-chores#29]
Setting the timezone Environment Variable in Rancher UI did not change the default UTC value.

thx

**Comment by funkyfuture** [comment]
could you please elaborate your cirumstances?

what's the output of a container inspection?
what's `deck-chore`'s logging output at debug level?

**Comment by HBO2** [comment]
Hi,

1. I am running the container in rancher 1.6
2. I have set the TIMEZONE: Europa/Amsterdam Environment Variable
`cron-scheduler:
    image: funkyfuture/deck-chores
    environment:
      TIMEZONE: Europe/Amsterdam
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always`

The simple log show this:
`
05/11/2017 13:09:37Deck Chores 0.2-rc2 started.
05/11/2017 13:09:372017-11-05 12:09:37,337|INFO    |Listening to events.
05/11/2017 13:09:372017-11-05 12:09:37,337|INFO    |Inspecting running containers.
05/11/2017 13:09:372017-11-05 12:09:37,502|INFO    |Added 'as-status-finished' for r-new-ain-app-cron-1-55855260
05/11/2017 13:09:372017-11-05 12:09:37,503|INFO    |Added 'project-approval-accept' for r-new-ain-app-cron-1-55855260
05/11/2017 13:09:372017-11-05 12:09:37,504|INFO    |Added 'project-approval-email' for r-new-ain-app-cron-1-55855260
05/11/2017 13:09:372017-11-05 12:09:37,504|INFO    |Added 'project-end-date' for r-new-ain-app-cron-1-55855260
05/11/2017 13:09:372017-11-05 12:09:37,505|INFO    |Added 'project-finished' for r-new-ain-app-cron-1-55855260`

**Comment by funkyfuture** [comment]
am i guessing right that the first snippet in your last response is a malformed docker-compose config?

if i undertand your initial problem description correctly, i would be especially interested in the first lines of deck-chores logs at debug level as its resolved config is documented right at startup.
