### ISSUE TITLE
Add tzdata package

### ISSUE THREAD

**Issue by prilka** [funkyfuture/deck-chores#33]
It's not possible to change the timezone via `TZ`-Env due to missing tzdata package.

Adding `apk add --no-cache tzdata` to your Dockerfile should fix the problem.

I think this was also the problem in #29

**Comment by funkyfuture** [comment]
could you please elaborate what your issue is when you use the [`TIMEZONE`](https://deck-chores.readthedocs.io/en/latest/usage.html#envvar-TIMEZONE) environment variable?

**Comment by prilka** [comment]
the `TIMEZONE` env works well for the scheduling. But the timezone is not set for the container-system. A simple `docker exec ..... date` will not print the expected date. This leads to wrong dates in `docker logs`.

**Comment by funkyfuture** [comment]
*if* i'm getting what you're aiming at, i don't understand how adding `tzdata` to the scheduling container would help with it.

**Comment by funkyfuture** [comment]
i'm closing the issue for now.

**Comment by TatzyXY** [comment]
The problem still exists and @prilka statement is right. The env. var `TZ` does not work.
Your container generally does work well and schedules to the right time but the missing env var `TZ` leads to some unexpected issues.

**Comment by funkyfuture** [comment]
@TatzyXY which version are you referring to?

**Comment by funkyfuture** [comment]
@TatzyXY thank you very much for your investigation. would you be so kind an open a PR?
