### ISSUE TITLE
Interval: daily - but which time?

### ISSUE THREAD

**Issue by maximkrusina** [funkyfuture/deck-chores#34]
Hi there, I really like this container. Also, the "interval" notation is nice, coz it's very easy to read, but...
...interval: daily

at which time is this task executed? At the midnight, or at the time of running the Docker container, or something else? Is it possible to specify exact time like:
...interval: daily at 3:00

Thanx!

**Comment by funkyfuture** [comment]
there should be no hidden functionality that is not documented. hence the `cron` trigger is what's left for your purpose.

**Comment by maximkrusina** [comment]
Understand, but still have no clue, when the "interval: daily" executed?

**Comment by funkyfuture** [comment]
i guess 14h after the job has been registered.
