### ISSUE TITLE
Alternative to handling missed execution

### ISSUE THREAD

**Issue by JEdCabanero** [funkyfuture/deck-chores#36]
I have multiple jobs that run every minute, and a less-needed job that runs every hour. 
I don't fully understand the code, but there doesn't seem to be a provision for handling missed executions other than skipping to the next one. 

I had a look at the underlying APScheduler library which powers this container, and it seems there are configurations for the features I described above. 

https://apscheduler.readthedocs.io/en/latest/userguide.html#missed-job-executions-and-coalescing

The first is misfire_grace_time it basically lists the number of seconds that is acceptable for a job to be late. 
The second is coalesce in the event the backlog has multiple identical scripts to run, coalesce will run one of those scripts in the backlog, and delete any identical backlogged scripts.

**Comment by funkyfuture** [comment]
under what conditions are "missed executions" occurring?

**Comment by JEdCabanero** [comment]
For reference: 

`2018-07-05 07:31:22,870|WARNING |Missed execution of orderscraper in scrapingtool_python at 2018-07-05 03:30:54.607287-04:00`

Altogether, there are a total of 5 scripts that run every minute, and it's interrupting somehow the execution of other scripts which are set to run every hour. 

What I would like to do is to set up the missed execution tolerance for the hourly scripts to be maybe 60 seconds, while the minute scripts have a delay of 10 seconds and configure this in the docker-compose.yml file alongside the job description information.

Backlogs of the minute scripts 2 or longer deep would execute once and delete duplicates.

**Comment by funkyfuture** [comment]
i still don't understand what the *condtitions* are for a job's execution to be missed.

since i assume that you don't restart *deck-chores* i can only guess that the executor's thread pool is empty. have you considered to invoke only one script per minute that calls other scripts?

adding a `coalesce` option per job seems doable.

**Comment by funkyfuture** [comment]
it would be very helpful if you provided more detailed configuration information and logs that have been captured in debug mode.

**Comment by funkyfuture** [comment]
closing due to missing feedback.

**Comment by Silex** [comment]
I found this: https://github.com/agronholm/apscheduler/issues/296, maybe you could increase `misfire_grace_time` ?

**Comment by funkyfuture** [comment]
thanks for your feedback, @Silex.

i can make much more sense of what's happening if you provided logs that were captured in debug mode and if you noted the times when the reboots actually happened.

this hasn't ever occurred with any of my deployments. my first guess would be that your system has a  high thread load when this occurs, please try to check on that.

the thing with setting the `misfire_grace_time` is that this is context-sensitive, e.g. for a job that runs every 30 seconds, your proposal could not make sense. 5 seconds might be reasonable, but i'm undecided on that.

i have currently no clue whether it would make sense to make this configurable in a job / container / image scope. i can add a global option, but i'm not keen on implementing the other possible scopes. well-crafted patches for reasonable use-case would be accepted.

oh, an rereading the thread, `coalesce` is to be considered. unfortunateley i missed that when i closed the issue.

**Comment by funkyfuture** [comment]
i added an option now that allows to configure a larger job executors pool size. that should address most cases where jobs are missed.

meanwhile i wouldn't mind to add a grace time option for missed jobs with a default 60 seconds and one option to set the `coalesce` behaviour, b/c i'd say that a continuously running process for jobs w/ a smaller interval would be better suited. at the same time these options would only(?) be useful for jobs that override these proposed defaults.

**Comment by Kelivan** [comment]
@funkyfuture Hi!
I encountered the same problem on one of the servers.
`
task_1        | 2023-10-01 02:00:04,929|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-01 02:00:00+03:00.
task_1        | 2023-10-03 02:00:05,236|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-03 02:00:00+03:00.
task_1        | 2023-10-05 02:00:02,213|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-05 02:00:00+03:00.
task_1        | 2023-10-07 02:00:03,978|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-07 02:00:00+03:00.
task_1        | 2023-10-08 02:00:01,656|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-08 02:00:00+03:00.
task_1        | 2023-10-11 02:00:05,651|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-11 02:00:00+03:00.
task_1        | 2023-10-12 02:00:01,836|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-12 02:00:00+03:00.
task_1        | 2023-10-14 02:00:04,225|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-14 02:00:00+03:00.
task_1        | 2023-10-15 02:00:01,409|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-15 02:00:00+03:00.
task_1        | 2023-10-18 02:00:06,149|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-18 02:00:00+03:00.
`
This task makes backups of PostgreSQL
`
labels:
  cron.db-dump.command: bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$$(date +"%Y%m%d")_portal.sql.gz"
  cron.db-dump.cron: "* * * * * 2 0 0"
`
Nothing interesting in the debug output
`
task_1        | 2023-10-14 02:00:04,107|DEBUG   |Looking for jobs to run
task_1        | 2023-10-14 02:00:04,199|DEBUG   |Next wakeup is due at 2023-10-15 02:00:00+03:00 (in 86395.802876 seconds)
task_1        | Run time of job "db-dump (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='2', minute='0', second='0'], next run at: 2023-10-15 02:00:00 MSK)" was missed by 0:00:04.183147
task_1        | 2023-10-14 02:00:04,225|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-14 02:00:00+03:00.
task_1        | 2023-10-15 02:00:01,400|DEBUG   |Looking for jobs to run
task_1        | 2023-10-15 02:00:01,405|DEBUG   |Next wakeup is due at 2023-10-16 02:00:00+03:00 (in 86398.594398 seconds)
task_1        | Run time of job "db-dump (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='2', minute='0', second='0'], next run at: 2023-10-16 02:00:00 MSK)" was missed by 0:00:01.406026
task_1        | 2023-10-15 02:00:01,409|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-15 02:00:00+03:00.
task_1        | 2023-10-16 02:00:00,000|DEBUG   |Looking for jobs to run
task_1        | 2023-10-16 02:00:00,006|DEBUG   |Next wakeup is due at 2023-10-17 02:00:00+03:00 (in 86399.993227 seconds)
task_1        | 2023-10-16 02:00:00,013|INFO    |portal-pg_postgresql_1: Executing 'db-dump'.
task_1        | 2023-10-16 02:00:00,381|DEBUG   |Daemon event: {'status': 'exec_start: bash -c rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +%Y%m%d)_portal.sql.gz', 'id': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'from': 'postgres:10-alpine', 'Type': 'container', 'Action': 'exec_start: bash -c rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +%Y%m%d)_portal.sql.gz', 'Actor': {'ID': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'Attributes': {'com.docker.compose.config-hash': 'f717fcd630129addf59ec0054e05bd8957a3bcd83af7ee6c3e992edc8045a114', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project': 'portal-pg', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.project.working_dir': '/docker/portal-pg', 'com.docker.compose.service': 'postgresql', 'com.docker.compose.version': '1.29.2', 'cron.db-dump.command': 'bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"', 'cron.db-dump.cron': '* * * * * 2 0 0', 'execID': '1a0edf89a99ea5a850b204226ca7972bfbe684dd0fd2b936ffa89410c92bf93e', 'image': 'postgres:10-alpine', 'name': 'portal-pg_postgresql_1'}}, 'scope': 'local', 'time': 1697410800, 'timeNano': 1697410800379213061}
task_1        | 2023-10-16 02:05:56,084|DEBUG   |Daemon event: {'status': 'exec_die', 'id': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'from': 'postgres:10-alpine', 'Type': 'container', 'Action': 'exec_die', 'Actor': {'ID': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'Attributes': {'com.docker.compose.config-hash': 'f717fcd630129addf59ec0054e05bd8957a3bcd83af7ee6c3e992edc8045a114', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project': 'portal-pg', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.project.working_dir': '/docker/portal-pg', 'com.docker.compose.service': 'postgresql', 'com.docker.compose.version': '1.29.2', 'cron.db-dump.command': 'bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"', 'cron.db-dump.cron': '* * * * * 2 0 0', 'execID': '1a0edf89a99ea5a850b204226ca7972bfbe684dd0fd2b936ffa89410c92bf93e', 'exitCode': '0', 'image': 'postgres:10-alpine', 'name': 'portal-pg_postgresql_1'}}, 'scope': 'local', 'time': 1697411156, 'timeNano': 1697411156066181725}
task_1        | 2023-10-16 02:05:56,102|INFO    |Command `bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"` in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb finished with exit code 0.
task_1        | 2023-10-17 02:00:00,017|DEBUG   |Looking for jobs to run
task_1        | 2023-10-17 02:00:00,098|INFO    |portal-pg_postgresql_1: Executing 'db-dump'.
task_1        | 2023-10-17 02:00:00,099|DEBUG   |Next wakeup is due at 2023-10-18 02:00:00+03:00 (in 86399.901019 seconds)
task_1        | 2023-10-17 02:00:00,452|DEBUG   |Daemon event: {'status': 'exec_start: bash -c rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +%Y%m%d)_portal.sql.gz', 'id': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'from': 'postgres:10-alpine', 'Type': 'container', 'Action': 'exec_start: bash -c rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +%Y%m%d)_portal.sql.gz', 'Actor': {'ID': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'Attributes': {'com.docker.compose.config-hash': 'f717fcd630129addf59ec0054e05bd8957a3bcd83af7ee6c3e992edc8045a114', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project': 'portal-pg', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.project.working_dir': '/docker/portal-pg', 'com.docker.compose.service': 'postgresql', 'com.docker.compose.version': '1.29.2', 'cron.db-dump.command': 'bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"', 'cron.db-dump.cron': '* * * * * 2 0 0', 'execID': '47fb14130a6e3054c27706c54dedab1c1789f32e720e4e94374b617de4095d00', 'image': 'postgres:10-alpine', 'name': 'portal-pg_postgresql_1'}}, 'scope': 'local', 'time': 1697497200, 'timeNano': 1697497200446706968}
task_1        | 2023-10-17 02:05:55,828|DEBUG   |Daemon event: {'status': 'exec_die', 'id': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'from': 'postgres:10-alpine', 'Type': 'container', 'Action': 'exec_die', 'Actor': {'ID': '2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb', 'Attributes': {'com.docker.compose.config-hash': 'f717fcd630129addf59ec0054e05bd8957a3bcd83af7ee6c3e992edc8045a114', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project': 'portal-pg', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.project.working_dir': '/docker/portal-pg', 'com.docker.compose.service': 'postgresql', 'com.docker.compose.version': '1.29.2', 'cron.db-dump.command': 'bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"', 'cron.db-dump.cron': '* * * * * 2 0 0', 'execID': '47fb14130a6e3054c27706c54dedab1c1789f32e720e4e94374b617de4095d00', 'exitCode': '0', 'image': 'postgres:10-alpine', 'name': 'portal-pg_postgresql_1'}}, 'scope': 'local', 'time': 1697497555, 'timeNano': 1697497555808353975}
task_1        | 2023-10-17 02:05:55,861|INFO    |Command `bash -c "rm -f /dump/* && pg_dump -O -Fp -b -U postgres portal | gzip > /dump/$(date +"%Y%m%d")_portal.sql.gz"` in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb finished with exit code 0.
task_1        | 2023-10-18 02:00:06,035|DEBUG   |Looking for jobs to run
task_1        | 2023-10-18 02:00:06,122|DEBUG   |Next wakeup is due at 2023-10-19 02:00:00+03:00 (in 86393.880049 seconds)
task_1        | Run time of job "db-dump (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='2', minute='0', second='0'], next run at: 2023-10-19 02:00:00 MSK)" was missed by 0:00:06.117066
task_1        | 2023-10-18 02:00:06,149|WARNING |Missed execution of db-dump in container 2264e9a1b35e784984d050b6f79496b425065761e1aa74bcfa25422ef720dcbb at 2023-10-18 02:00:00+03:00.
`
I think it would be a good idea to add a grace time option to the variables.
