### ISSUE TITLE
running into a swarm

### ISSUE THREAD

**Issue by Sadrak** [funkyfuture/deck-chores#45]
Hi everone,

i tried using deck-chores in a swarm multiple times on a node (with different LABEL_NAMESPACE's and so far everything works. The only thing I changed is the `there_is_another_deck_chores_container` method to return always false. I guess if I change this to check against LABEL_NAMESPACE's in the containers Environment (or if empty like the normal behavior) it should be possible to run as many deck-chores you like in a swarm on every node.

Or did i miss something?

**Comment by Sadrak** [comment]
for the curious: We need different TIMEZONE-Settings for different services.
```
scheduler-UTC.test.command: echo hello
scheduler-UTC.test.cron: 4 0 0
scheduler-Europe-Berlin.test.command: echo hello
scheduler-Europe-Berlin.test.cron: 4 0 0
```

**Comment by funkyfuture** [comment]
thanks for the feedback.

my assumption would be that a swarm daemon would return all events that happen in that cluster,  hence one `deck-chores` instance would suffice. or am i wrong with that?

> We need different TIMEZONE-Settings for different services.

can you elaborate that? with your example, you have employed multiple instances with individual `LABEL_NAMESPACE`s assigned, right?

**Comment by Sadrak** [comment]
I am not familar with docker internals, but I tried many things the last 2 days and from my view everything work as expected. The deck-chores on every node only manage containers with matching LABEL_NAMESPACE on the same node.

Here is my current test for schedulers:
```yml
version: "3.6"

services:
    UTC:
        image: own-deck-chores:latest
        environment:
            TIMEZONE: UTC
            LABEL_NAMESPACE: scheduler-UTC
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: global

    Europe-Berlin:
        image: own-deck-chores:latest
        environment:
            TIMEZONE: Europe/Berlin
            LABEL_NAMESPACE: scheduler-Europe-Berlin
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: global
```

**Comment by Sadrak** [comment]
i am also not familar with python, perhaps someone can easily rewrite this one check to search for the LABEL_NAMESPACE on the same node?

**Comment by funkyfuture** [comment]
sorry for the delayed answer. thanks for providing more information, i get a sense what you're doing, but i don't understand the rationale yet. in fact there are two issues.

1) why are you deploying in global mode?

that means that `deck-chores` runs on each of your nodes. is that necessary? you can find out by running `deck-chores` in debug mode and watch whether it handles events (e.g. container starts) on another node.

2) why are you using distinct instances for distinct time zones?

that `TIMEZONE` tells the scheduler which timezone the system clock is providing its time from. it also serves as default for jobs that do not specify a timezone.

**Comment by Sadrak** [comment]
> sorry for the delayed answer. thanks for providing more information, i get a sense what you're doing, but i don't understand the rationale yet. in fact there are two issues.
> 
> 1. why are you deploying in global mode?
> 
> that means that `deck-chores` runs on each of your nodes. is that necessary? you can find out by running `deck-chores` in debug mode and watch whether it handles events (e.g. container starts) on another node.

Also without debug I can see in the logs, that only the `deck-chore` on the corresponding node receive the labels from a new container (and then setup the invocation for a cron). The `deck-chores` on the other nodes did not react when a new container arrive.

Also i tried now the DEBUG=yes mode and I can't see the events from the other node in the logs. Perhaps your assumption is not correct? Did you have some hint from the code that this behavior is wrong?

> 
> 1. why are you using distinct instances for distinct time zones?
> 
> that `TIMEZONE` tells the scheduler which timezone the system clock is providing its time from. it also serves as default for jobs that do not specify a timezone.

My tests here are not done, but i hope to solve the following problem. CET VS CEST are not applicable with only an UTC cron.

We want to run most crons via UTC, but some crons need a specific drifting TIMEZONE like Europe/Berlin. The cron must run daily at 10:00 and that is 09:00 UTC or perhaps 08:00 UTC.

**Comment by Sadrak** [comment]
Can I perhaps help at some point?

**Comment by funkyfuture** [comment]
> Can I perhaps help at some point?

sorry, but i need time. to study Docker Swarm.

> The cron must run daily at 10:00 and that is 09:00 UTC or perhaps 08:00 UTC.

okay, but it should suffice to set the job's timezone to `CET` and not to run multiple schedulers.

**Comment by Sadrak** [comment]
> > The cron must run daily at 10:00 and that is 09:00 UTC or perhaps 08:00 UTC.
> 
> okay, but it should suffice to set the job's timezone to `CET` and not to run multiple schedulers.

Sorry, I can't follow your explanation. Why not start multiple schedulers? With different LABEL_NAMESPACE settings everything works smooth and as expected.

I need on the same system this possibilities:
* run a job at 00:00:00 @UTC
* run a job at 00:00:00 @Europe/Berlin (which is CET/CEST ; depends on DST)

**Comment by funkyfuture** [comment]
hey, sorry for the longer delay. i'll probably dig into the swarm thing on the weekend. to get it right, how are you actually deploying the services, with `docker-compose up` or `docker stack deploy`?

**Comment by Sadrak** [comment]
With docker stack deploy

Frank Sachsenheim <notifications@github.com> schrieb am Do., 30. Jan. 2020,
23:49:

**Comment by funkyfuture** [comment]
okay, here are my findings regarding Swarm:

1. if you use `deck-chores` on a Docker swarm, it must be deployed in `global` mode in order to run jobs of all the task (Swarm terminology) instances that manifest as containers.
1. however, this will disable the ability to restrict jobs to run on only one instance (let's call this *singleton jobs* further on). this feature is essential for jobs like backups and data ingestions, actually i can't think of any useful job that wouldn't require this.
1. in order to not lose thise feature, `deck-chores` instances on all nodes would have to coordinate which of them runs a singleton job. that would require a whole new architecture for `deck-chores`.

----

i think this addresses your dst question: https://apscheduler.readthedocs.io/en/stable/modules/triggers/cron.html#daylight-saving-time-behavior

----

i'll add notes in both regards to the docs.

**Comment by Sadrak** [comment]
> okay, here are my findings regarding Swarm:
> 
> 1. if you use `deck-chores` on a Docker swarm, it must be deployed in `global` mode in order to run jobs of all the task (Swarm terminology) instances that manifest as containers.

We start deck-chores in global mode, yes.

> 2. however, this will disable the ability to restrict jobs to run on only one instance (let's call this _singleton jobs_ further on). this feature is essential for jobs like backups and data ingestions, actually i can't think of any useful job that wouldn't require this.

From my experience it is restricted by max one job per host-system. And this is exactly what we need. I understand the problematic aspect when running a backup job within a container that is deployed more then 1 time in a swarm. But please don't ignore our use case.

> 3. in order to not lose thise feature, `deck-chores` instances on all nodes would have to coordinate which of them runs a singleton job. that would require a whole new architecture for `deck-chores`.

In my option this is not required. It should simple documented, how this is running in swarm mode.

And for this i would really love to see `there_is_another_deck_chores_container` patched to be usefull in swarm mode.

> 
> i think this addresses your dst question: https://apscheduler.readthedocs.io/en/stable/modules/triggers/cron.html#daylight-saving-time-behavior
> 
> i'll add notes in both regards to the docs.

**Comment by funkyfuture** [comment]
> From my experience it is restricted by max one job per host-system. And this is exactly what we need. … But please don't ignore our use case.

it'd be easier to not ignore it if i knew it. what kind of job is suited to run on all instances of a service?

> In my option this is not required. It should simple documented, how this is running in swarm mode.

but that is a key feature, otherwise it would ignore the common use-case of a backup.

> And for this i would really love to see `there_is_another_deck_chores_container` patched to be usefull in swarm mode.

this has nothing to do with the swarm mode, but with that dst-issue, right? do i understand you snippets correctly, that you want to have the same job run by two different `deck-chores` instances that are configured for two different timezones at the same time?

**Comment by Sadrak** [comment]
> > From my experience it is restricted by max one job per host-system. And this is exactly what we need. … But please don't ignore our use case.
> 
> it'd be easier to not ignore it if i knew it. what kind of job is suited to run on all instances of a service?

It's kind of cleanup, managing and notification jobs. Some of them could be rewritten as another service, but i like the concept of cronjobs and think this is easier to maintain.


> 
> > In my option this is not required. It should simple documented, how this is running in swarm mode.
> 
> but that is a key feature, otherwise it would ignore the common use-case of a backup.
> 
> > And for this i would really love to see `there_is_another_deck_chores_container` patched to be usefull in swarm mode.
> 
> this has nothing to do with the swarm mode, but with that dst-issue, right? do i understand you snippets correctly, that you want to have the same job run by two different `deck-chores` instances that are configured for two different timezones at the same time?

No, i think that is not my usecase (or i misunderstood you).

We have different namespaces so we can start multipe instances of deck chores on one host with different timezone settings. We want to start only one managing process for one service, but we need for one project Europe/Berlin (CET<->CEST) and for the other UTC.

**Comment by funkyfuture** [comment]
> It's kind of cleanup, managing and notification jobs.

that would mean duped notifications in the case where a service is scaled to more than instance. is my proposal in #48 comprehensible?

> We have different namespaces so we can start multipe instances of deck chores on one host with different timezone settings.

this i understood. i'm not grasping the motivation.

> but we need for one project Europe/Berlin (CET<->CEST) and for the other UTC.

then why don't you configure different timezones for the jobs per project?

**Comment by Sadrak** [comment]
> > It's kind of cleanup, managing and notification jobs.
> 
> that would mean duped notifications in the case where a service is scaled to more than instance. is my proposal in #48 comprehensible?
> 
> > We have different namespaces so we can start multipe instances of deck chores on one host with different timezone settings.
> 
> this i understood. i'm not grasping the motivation.
> 
> > but we need for one project Europe/Berlin (CET<->CEST) and for the other UTC.
> 
> then why don't you configure different timezones for the jobs per project?

uh, perhaps i simple overread this possibilty ... so i simple have to add `.env.TIMEZONE`?

```
    labels:
      deck-chores.clear-caches.command: do-it.sh
      deck-chores.clear-caches.interval: 03 00 00
      deck-chores.clear-caches.env.TIMEZONE: Europe/Berlin
```
and

```
    labels:
      deck-chores.clear-caches.command: do-it.sh
      deck-chores.clear-caches.interval: 03 00 00
      deck-chores.clear-caches.env.TIMEZONE: UTC # or leave if UTC is the configured default
```

**Comment by funkyfuture** [comment]
that would be effective as environment variable in the context of the job execution inside the container. for the scheduler it is a job's `timezone` attribute as documented here: https://deck-chores.readthedocs.io/en/stable/usage.html#job-definitions

if you feel that the docs could be extended w/ examples, please open a pr.

**Comment by funkyfuture** [comment]
the timezone doesn't matter for `interval` triggers.

**Comment by funkyfuture** [comment]
i'm considering this solved. since it was about two different issues, please open new ones for follow-ups.
