### ISSUE TITLE
Docker tah latest not available anymore

### ISSUE THREAD

**Issue by maximkrusina** [funkyfuture/deck-chores#50]
Plz, can we use again the atest tag? It's a liitle bit standard. Thanx!!!

**Comment by funkyfuture** [comment]
what would be the advantage over specifying the desired version (e.g. `funkyfuture/deck-chores:1`)?

**Comment by maximkrusina** [comment]
It's the de-facto standard for most of the Docker packages. When upgrading our systems, it's clearly visible that we don't need to stick to a particular version and that we're happy with the latest production version. Useful a lot - it's clearly visible in the docker-compose file. Otherwise, without latest tag,  admin have to go thru all docker images and check if there is a newer version manually.

**Comment by funkyfuture** [comment]
i do not agree. a new major version of a good product would probably break your configuration, a new minor version may introduce functionalities that may be a good reason to adapt a configuration. hence using the `latest` tag 

> admin have to go thru all docker images and check if there is a newer version manually.

that fits my understanding of a responsible sysadmin. with the final release out, `funkyfuture/deck-chores:1` is de-facto equivalent to the (omitted) `…:latest` variant.

beside that pitfall, it would also be cumbersome to build, (a `0.9.1` wouldn't be supposed to be `latest` if there is already a `1.0`, but it's released after that, right?) which would make the current build process that relies on four interdependent systems even more shaky.

**Comment by funkyfuture** [comment]
since i couldn't be convinced to change that aspect, i'm closing this issue.

**Comment by madleech** [comment]
I understand your reasoning for not including the `:latest` tag, however now the clearly displayed instructions in the sidebar of Docker Hub are wrong:
![screenshot-hub docker com-2020 05 12-10_40_48](https://user-images.githubusercontent.com/1756799/81619188-1b4a6e00-943d-11ea-9095-765b38440f33.png)

Running them gives:
```
 > docker pull funkyfuture/deck-chores
Using default tag: latest
Error response from daemon: manifest for funkyfuture/deck-chores:latest not found: manifest unknown: manifest unknown
```

Can you please correct the command in the sidebar.

**Comment by maximkrusina** [comment]
I still believe that it's always good to allow to use docker images without specifying the exact version, it's de-facto docker standard, so for me "docker pull funkyfuture/deck-chores" is really good standard and best practice and should be kept. Sure, there is lot of reasons why is useful to specify major/minor version when pulling images, but this should be left on user's responsibility... just my point of view.
