### ISSUE TITLE
ERROR not logged to STDERR

### ISSUE THREAD

**Issue by Sadrak** [funkyfuture/deck-chores#55]
We encounter some STDOUT/STDERR problems.

The following messages are printed to STDOUT:

```
2020-04-08 12:59:53,609|ERROR   |Misconfigured job definition: {'command': 'ls', 'cron': '20', 'name': 'UPPERCASE', 'user': ''}
2020-04-08 12:59:53,609|ERROR   |Errors: {'name': ["value does not match regex '[a-z0-9.-]+'"]}
```

```
{"log":"2020-04-08 12:59:53,609|ERROR   |Misconfigured job definition: {'command': 'ls', 'cron': '20', 'name': 'UPPERCASE', 'user': ''}\n","stream":"stdout","time":"2020-04-08T12:59:53.609464237Z"}
{"log":"2020-04-08 12:59:53,609|ERROR   |Errors: {'name': [\"value does not match regex '[a-z0-9.-]+'\"]}\n","stream":"stdout","time":"2020-04-08T12:59:53.609658025Z"}
```

We would love to see this messages at STDERR (because STDERR get more attention).

Also why are not uppercase characters allowed? Is there a good reason for that?

**Comment by funkyfuture** [comment]
1) log output

am i getting your request correctly, that you  want only messages at error level separated to stderr? or would be a redirection of all logging be sufficient in your use-case?

are you running `deck-chores` in a Docker container or natively on the host?

2) job name constraint

yes, this is intended (and not documented) to enforce a style i consider preferable and in alignment with the compose file schema. all-uppercase tokens should be used for environment variable names. it also eliminates the slight risk of errors caused by mistakes by mistyping or the usage of different forms in various places (declarations in images and overrides for containers).

i'd like to keep (and document) it this way, unless there's a legit use-case that couldn't be achieved otherwise.

**Comment by Sadrak** [comment]
Sorry for the long delay.



> 1. log output
> 
> am i getting your request correctly, that you want only messages at error level separated to stderr? or would be a redirection of all logging be sufficient in your use-case?

I would propose to log everything >= WARN (WARN, ERROR, FATAL, ...) only to STDERR and not STDOUT. This feels more natural and give better/simpler processing possibilities.

> 
> are you running `deck-chores` in a Docker container or natively on the host?

in a container


> 
> 1. job name constraint
> 
> yes, this is intended (and not documented) to enforce a style i consider preferable and in alignment with the compose file schema. all-uppercase tokens should be used for environment variable names only. it also eliminates the slight risk of errors caused by mistakes by mistyping or the usage of different forms in various places (declarations in images and intended overrides for containers).
> 
> i'd like to keep (and document) it this way, unless there's a legit use-case that couldn't be achieved otherwise.

No, i am fine with such a documented feature. But generell i try to avoid such homemade limitations. In most cases you only break someone else name convention without a good reason. I understand your intention, but i think this is more suitable as a nameing convention in a project, not a forced limitation in a software.

**Comment by funkyfuture** [comment]
my time is very limited atm. could you look into an implementation? my only concern would be that messages might get lost for Docker(-Compose)'s logging facility (that might use `journald` as backend for example). if this wouldn't be implied by such change, go for it. a configuration option that tells `deck-chores` which log level is the minimum that ends up in `stderr` would be neat.

**Comment by Sadrak** [comment]
can you perhaps guide me to the relevant code?

This week this behavior hit us again and i am planing to make a PR.

**Comment by Sadrak** [comment]
got it, this looks possible for me.

**Comment by Sadrak** [comment]
Question: What is about the STDERR from the job?

Currently STDOUT & STDERR get captured and printed to STDOUT, would you accept an option to configure this? Or change this complete?

**Comment by funkyfuture** [comment]
hmm, before i can develop an opinion, let me ask this: you write that `deck-chores` is running in a container and that the STDERR get more attention. how do you facilitate this? so far i only built Docker setups where all stdout is captured either in json-files or by `journald`. afaik both do not provide a way to look specifically at STDERR output.
