### ISSUE TITLE
Issue with command trigger with valid cron

### ISSUE THREAD

**Issue by eancuta** [funkyfuture/deck-chores#58]
I have a build configuration for mongodb in my docker-compose.yml file.

I have added the following section to the labels:

> deck-chores.label-name-one.command: "mongo localhost:27017/myDB /scripts/aggregate-script.js"
> deck-chores.label-name-one.cron: "14,29,44,59 * * * *"

Based on the cron, I would expect my script to run every 14th, 29th, 44th and 59th minute.

I have tried changing the cron part to "*/1 * * * *" and the script runs successfully every minute.

Is there a possible issue parsing this cron properly? As I understand it is via APScheduler and they seem to support the comma notation.

**Comment by funkyfuture** [comment]
does [this help](https://deck-chores.readthedocs.io/en/stable/usage.html#cron)?

> In contrast to the classic, the sequence of fields is flipped, starting with the greatest unit on the left.

**Comment by eancuta** [comment]
> does [this help](https://deck-chores.readthedocs.io/en/stable/usage.html#cron)?
> 
> > In contrast to the classic, the sequence of fields is flipped, starting with the greatest unit on the left.

I read those docs multiple times but somehow skipped past it thinking "ah yeah business as usual"

Thanks for pointing it out specifically, I will give it a test and then if it works okay, I will close this issue

**Comment by eancuta** [comment]
I used "14,29,44,59 0" and now it works, sorry for the inconvenience and thanks again for pointing to where I need to look :+1:
