### ISSUE TITLE
How to run deck-chores in Kubernetes environment?

### ISSUE THREAD

**Issue by jkabat** [funkyfuture/deck-chores#60]
I defined deck-chores as DaemonSet to have running one instance of this image per cluster node.

Tasks are properly registered, but somehow each execution fails with 
```bash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
```

During a quite long debugging session I found out that container ID which is used for executing a task is actually not the right container, rather a kubelet container with base image k8s.gcr.io/pause:3.2

Is there any chance to make deck-chores work in kubernetes? Is it even possible?

**Comment by funkyfuture** [comment]
afaict k8s doesn't expose the same interface as Docker and to make deck-chores work properly with Swarm would even require a major refactoring.
