### ISSUE TITLE
Move images to a self-hosted registry

### ISSUE THREAD

**Issue by funkyfuture** [funkyfuture/deck-chores#61]
w/ Docker's announcement of limited image retention it seems to be a good idea to host the images on a self-hosted registry.

i'd be interested in other possible hosts nonetheless.

**Comment by Rillke** [comment]
> i'd be interested in other possible hosts nonetheless.

Collegues from Munster WWU use quay.io. GitHub appears to have a [registry built-in as part of their GitHub Packages Feature](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

**Comment by funkyfuture** [comment]
thanks for the hints. after switching to GitHub actions for the quality tests, it seems nearby to use it for building and distributing images. that'd imply to address #46 as well. (though i like the Entschleunigung that building on actual hardware provides.)

meanwhile Docker stepped back to some degrees with the announced changes. nonetheless, if someone has experience with GitHub's facilitation i'd appreciate initial proposals that leverage it in a pull request.
