### ISSUE TITLE
Add support to manage jobs against docker node itself

### ISSUE THREAD

**Issue by markfqs** [funkyfuture/deck-chores#63]
First let me congrat as I found deck-chores simple-effective for the purpose.

One common required maintenance task is to periodically prune docker unused images, volumes or dangling containers.

Taking advantage of having deck-chores running on all swarm-nodes (deploy: global) with the docker-socket available is a good candidate to schedule these (and potentially other) jobs. However there is no command available on the image (curl, socat,...) to make requests to its own docker-socket.

The simplest way would be to simply add curl package on the image and setup a schedule like:

    curl --unix-socket /var/run/docker.sock -X POST http://node/volumes/prune

I could build my own image just from deck-chores and add that package, however I think it could be a great enhancement to provide some sort of method out-of-the-box.

I'm thinking to be able to configure (either via labels, config file or environment) deck-chores itself with something like:

    deck-chores.docker.vol.request: /volumes/prune?filter=until=168h
    deck-chores.docker.vol.cron: "0 3 0 0"
    deck-chores.docker.net.request: /network/prune
    deck-chores.docker.net.cron: "0 3 0 0"

Scheduling tasks on deck-chores itself against the docker socket would open another field of possibilities like scaling services on periods, launching on-shot containers, ...

Again I could simply add 'curl' to my own image, but I though it may be an interesting feature to implement.

Regards

**Comment by funkyfuture** [comment]
thanks for the feedback. i think it's best that you deploy containers with `curl` or a Docker client installed that are then controlled by `deck-chores`. `deck-chores` has one purpose and none will be added.
