### ISSUE TITLE
Date parsing exception, again

### ISSUE THREAD

**Issue by Bensge** [funkyfuture/deck-chores#70]
I'm experiencing almost the same problem as described in #66 .
Version used: latest at the time of writing, 1.1.11
OS: Debian 10.9
Docker version 20.10.5

The crash happens during date format parsing:
```
Deck Chores 1.1.11 started.
2021-05-19 07:53:04,324|INFO    |Inspecting running containers.
2021-05-19 07:53:04,398|INFO    |stag-container.xyzr: Added 'regular-task' (xxxxxxxxxxxxxxx).
2021-05-19 07:53:04,443|ERROR   |Caught unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 301, in main
    last_event_time = inspect_running_containers()
  File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 105, in inspect_running_containers
    datetime.fromisoformat(started_at[: 23 if len(started_at) < 26 else 26]),
ValueError: Invalid isoformat string: '2021-05-17T20:07:58.54095Z'
```
Is the time zone identifier Z at the end of the date string the problem? Maybe we should be using a more robust date parser.

This seems to be a well-known limitation of pythons built-in `datetime` class. Some workarounds are also shown here: https://discuss.python.org/t/parse-z-timezone-suffix-in-datetime/2220

**Comment by funkyfuture** [comment]
thanks for reporting and the research!

> Maybe we should be using a more robust date parser.

from the three repos mentioned in the thread, [this](https://github.com/tonyg/python-rfc3339) seems sufficient, but i can't find a release in the cheeseshop. vendorizing it is an option though.

have you found something that may be better suited?

with an extra function call, all forms that are datestrings encountered in the wild can be tested.

and the not testing seems to be the problem here, because my impression is that this is the same bug as in #66 and my solution was just naive.

**Comment by Bensge** [comment]
What about using the `dateutil` library? 
As shown in the python discussion, it can be used like this:
```python
>>> from dateutil import parser
>>> parser.isoparse('2019-08-28T14:34:25.518993Z')
datetime.datetime(2019, 8, 28, 14, 34, 25, 518993, tzinfo=tzutc())
```
The library is apparently maintained by a python standard library contributor and it's quite popular.

I can perform tests in my server environment where the bug occurs. I develop on macOS and the toolchain to build the docker image is broken here, that's my problem

**Comment by funkyfuture** [comment]
yes. i'll probably change it on Sunday and release a patch release as well.

**Comment by funkyfuture** [comment]
thank you! this should be fixed w/ a3b40f3c0d9e4f79b3db5a1952da1cd8e08d9f7e and is included in the 1.1.12 release.

**Comment by Bensge** [comment]
Thank you for the fix. Unfortunately a new issue showed up. Because the new date parser returns a timezone-aware `datetime` (at least on my setup), it's not possible to compare it to a `datetime` without a time zone (unaware) anymore. See the exact error here:
```
| Deck Chores 1.1.12 started.
| 2021-05-25 07:27:14,567|INFO    |Inspecting running containers.
| 2021-05-25 07:27:14,579|ERROR   |Caught unhandled exception:
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 301, in main
|     last_event_time = inspect_running_containers()
|   File "/usr/local/lib/python3.9/site-packages/deck_chores/main.py", line 101, in inspect_running_containers
|     last_event_time = max(
| TypeError: can't compare offset-naive and offset-aware datetimes
```

The parsed `datetime` is compared to the result of `datetime.utcnow()`, which doesn't have a time zone per definition. 
> classmethod datetime.utcnow()
> Return the current UTC date and time, with tzinfo None.
> This is like now(), but returns the current UTC date and time, as a naive datetime object. An aware current UTC datetime can be  obtained by calling datetime.now(timezone.utc). See also now().
[source](https://docs.python.org/3/library/datetime.html)

I think we need one more iteration to fix the issue

**Comment by funkyfuture** [comment]
thanks, see #72.

**Comment by Bensge** [comment]
Thank you for the quick response. Deck-chores is now running fine on my server 😄

**Comment by funkyfuture** [comment]
i'm glad to hear that. sorry for the inconvenience, but eventually it was a useful renovation.
