### ISSUE TITLE
Feature suggestion: Send job output by mail

### ISSUE THREAD

**Issue by markfqs** [funkyfuture/deck-chores#85]
Subjects says it all,

Although one could check the logs, capturing the output of logs and optionally sending it by mail to a predefined address would be a great enhancement.

I think that the SMTP (server, from address, ) could be set/configure don deck-chores itself, and then via labels be able to define if send always, never, onerror and the recipient address.

**Comment by funkyfuture** [comment]
no, the subject doesn't say all, as your following elaboration shows.

i'm open to anything that would improve the situation for auxillary software components that process the logs, but there will be no builtin smtp support.
