### ISSUE TITLE
Use SHA256 digest instead of tag for base image.

### ISSUE THREAD

**Issue by bddenhartog** [funkyfuture/deck-chores#9]
Tags are mutable, digests are immutable. The digest for `python:3.6-alpine` should be preferred over the tag.

**Comment by funkyfuture** [comment]
what's the rationale behind this? the image builds shall always base on the most recent parent builds.

**Comment by bddenhartog** [comment]
> the image builds shall always base on the most recent parent builds.

Right, which isn't what you want in terms of consistency. Immutability is preferred for the the same reason you chose to base your image off of `python:3.6-alpine` instead of `python:alpine`. Without the digest, you cannot confirm that you're starting off from the same image.

In turn, `python:*-alpine` images are based off of `alpine:3.4`. If a regression or backwards-incompatible change is made to `alpine` (because of some dire security issue, for example) and the resulting image is re-tagged `alpine:3.4`, your image now extends the new parent with a change that broke/modified your process(es).

I suppose you could make the argument that you test the image before it's pushed to the registry, and if you're comfortable with that process then using the digest doesn't serve any purpose for you. Using the digest simply adds another layer of immutability to help prevent against image mutations.

**Comment by funkyfuture** [comment]
yep, i'm fine with that.
